### ISSUE TITLE
import hook

### ISSUE THREAD

**Issue by wbolster** [adamchainz/patchy#299]
hi, thanks for this cool project. if it didn't exist i may have ended up writing something like this myself one day :smile:

that said, it seems `patchy` is not evil 😈 enough for all use cases. more specifically, it seems not possible to do import-time patching. this is useful to suppress import-time warnings from libraries that haven't been updated to the latest python version, or to modify code that misbehaves at import time.

python's importlib has import hooks which seem to open the possibility for a feature like this.

do you have any thoughts on that? (or are you aware of related projects that do this?)

**Comment by adamchainz** [comment]
Hi, thanks for enjoying patchy!

To do things at interpreter startup, you can use `sitecustomize`, `usercustomize`, or a `.pth` file. See [PEP 648 motivations](https://www.python.org/dev/peps/pep-0648/#motivation), [the site docs](https://docs.python.org/3/library/site.html) and [this video on pth files](https://www.youtube.com/watch?v=mzxQrgvuRFg).

Hope that helps,

Adam

**Comment by wbolster** [comment]
yeah, i got that already — this issue was to inquire whether patching at import-time would be in scope for this package. (since the diff-based approach is a bit involved at first but safer to evolve over time.)

**Comment by adamchainz** [comment]
No it's not in scope, just call patchy with one of the above methods.
