### ISSUE TITLE
replacing function rather than patching

### ISSUE THREAD

**Issue by rofl0r** [adamchainz/patchy#77]
seems too much hassle to create a proper patch for a small function.
how about an additional `replace` function ?

```py
def foo():
 return 1
patchy.replace(foo, 'def foo():\n return 42\n')
```

**Comment by adamchainz** [comment]
PR welcome

**Comment by rofl0r** [comment]
oh. i thought it would take you like 2 mins to implement it
from
```
old= get_old_code()
new = apply_patch(old, diff)
exchange(old, new)
```
to
```
old= get_old_code()
new = arg2
exchange(old, new)
```
anyway, if that's asked too much i can have a look at it.

**Comment by adamchainz** [comment]
It's not hard but I don't have time right now

**Comment by rofl0r** [comment]
i was curious how it works internally so i gave it a shot ^

**Comment by adamchainz** [comment]
It's horrible, isn't it? 😁

**Comment by rofl0r** [comment]
well, i'm quite a python noob but it looks quite good. the only thing that struck me was the kludge of having to make a patch, and the effort involved in that (running an external program, and caching its output for speed).

**Comment by adamchainz** [comment]
We've had attempts to use a Python-based patching library but it wasn't great. Turns out patch files aren't easy.

**Comment by rofl0r** [comment]
which makes me think that it may not be a bad idea to create a python patch library on top of an existing C implementation (i.e. calling out to C functions instead of running an exe), but there may be licensing implications.
